# This workflow will build a Java project with Maven

name: Java CI with Maven

on:
  push:
    paths-ignore:
    - 'README.md'
    - '.gitignore'
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2.5.0
      with:
        java-version: 1.8
    - name: Setup Git
      run: |
        git config --global user.name github-actions
        git config --global user.email github-actions@github.com
    - name: Build with Maven
      run: ./mvnw -B clean install
