# This workflow will build a Java project with Maven

name: Java CI with Maven [PR]

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3.1.0
      with:
        java-version: 1.8
    - name: Setup Git
      run: |
        git config --global user.name github-actions
        git config --global user.email github-actions@github.com
    - name: Build with Maven
      run: ./mvnw -B clean install
